# Generated by Django 2.2.2 on 2020-04-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='relation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_journal_relation_+', to='journal.Journal', verbose_name='関連'),
        ),
    ]
