# Generated by Django 2.2.2 on 2020-05-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20200405_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
