# Generated by Django 2.2.2 on 2020-04-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='relation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_journal_relation_+', to='journal.Journal', verbose_name='関連記事'),
        ),
    ]
