# Generated by Django 2.2.2 on 2020-05-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journal_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='count',
        ),
    ]
