# Generated by Django 2.2.2 on 2020-05-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_remove_journal_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='timestamp',
        ),
    ]
